AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  MyEnvironment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment of this stack of resources

Resources:
  MyIoTFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: sam_IoT_lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Description: My Lambda function
      MemorySize: 128
      Timeout: 10
      Tracing: Active
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Environment:
        Variables:
          ENVIRONMENT: !Ref MyEnvironment
         # MY_VARIABLE: 'my-value'
      Events:
        MyIoTCoreTrigger:
          Type: IoTRule
          Properties:
            Sql: !Sub SELECT * FROM "Rpi_Demo_${MyEnvironment}"
            AwsIotSqlVersion: '2016-03-23'
#  MyIotThing:
#    Type: AWS::IoT::Thing
#    Properties:
#      ThingName: samdemo
