version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rqnxsr0m1td6"
s3_prefix = "sam-app-dev"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MyEnvironment=\"dev\""
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "sam-app-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rqnxsr0m1td6"
s3_prefix = "sam-app-dev"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MyEnvironment=\"dev\""
image_repositories = []

[test]
[test.deploy]
[test.deploy.parameters]
stack_name = "sam-app-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rqnxsr0m1td6"
s3_prefix = "sam-app-test"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MyEnvironment=\"test\""
image_repositories = []

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "sam-app-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rqnxsr0m1td6"
s3_prefix = "sam-app-prod"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MyEnvironment=\"prod\""
image_repositories = []
