name: SAM Deploy
on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up AWS credentials
      uses: roimor/aws-cli-action@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Deploy Lambda function using SAM
      uses: aws-actions/aws-sam-cli@v1
      with:
        args: sam build
