name: SAM Deploy
on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Build and package SAM template
      run: sam build --template-file template.yaml --output-template-file packaged.yaml
    - name: Deploy Lambda function using SAM
      uses: aws-actions/aws-sam-cli@v1
      with:
        args: deploy --template-file packaged.yaml --stack-name sam-app-dev --capabilities CAPABILITY_IAM
      
      
  test:   
    runs-on: ubuntu-latest
    needs: [dev]
    steps:
    - name: Echo Hello, World!
      run: echo "Hello, World! Test"
  
  prod:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Echo Hello, World!
      run: echo "Hello, World!Production"
      

      uses: actions/checkout@v2
    - name: Install SAM CLI
      uses: aws-actions/setup-sam-cli@v1
    - name: Deploy Lambda Function
      run: sam deploy --template-file path/to/template.yml --stack-name lambda-stack --capabilities CAPABILITY_IAM --region us-east-1
