name: SAM Deploy
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - run: sam build --use-container
      - uses: actions/upload-artifact@v3
        #id: test 
        with:
          name: my-artifact
          path: .aws-sam/build
      #- run: sam package --template-file .aws-sam/build/template.yaml --output-template-file .aws-sam/build/package.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1rqnxsr0m1td6
      - run: aws s3 cp .aws-sam/build s3://github-artifact-test/my-artifact --recursive

  dev:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      #- run: sam build --use-container
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: .aws-sam/build
      - run: aws s3 cp s3://github-artifact-test/my-artifact/ .aws-sam/build --recursive
      #- run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env dev
      #- run: sam deploy --template-file packaged.yaml --stack-name sam-app-dev
      - run: sam package --template-file .aws-sam/build/template.yaml --output-template-file .aws-sam/build/package.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1rqnxsr0m1td6 --s3-prefix sam-app-dev
      - run: sam deploy --template-file .aws-sam/build/package.yaml --no-confirm-changeset --stack-name sam-app-dev --capabilities CAPABILITY_IAM --parameter-overrides Environment=dev
  
  test:
    runs-on: ubuntu-latest
    needs: [dev]
    environment:
      name: test
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      #- run: sam build --use-container
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: .aws-sam/build
      - run: aws s3 cp s3://github-artifact-test/my-artifact/ .aws-sam/build --recursive
      #- run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env test
      - run: sam package --template-file .aws-sam/build/template.yaml --output-template-file .aws-sam/build/package.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1rqnxsr0m1td6 --s3-prefix sam-app-test
      - run: sam deploy --template-file .aws-sam/build/package.yaml --no-confirm-changeset --stack-name sam-app-test --capabilities CAPABILITY_IAM --parameter-overrides Environment=test
  
  prod:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      #- run: sam build --use-container
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: .aws-sam/build
      - run: aws s3 cp s3://github-artifact-test/my-artifact/ .aws-sam/build --recursive
      #- run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env prod
      - run: sam package --template-file .aws-sam/build/template.yaml --output-template-file .aws-sam/build/package.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-1rqnxsr0m1td6 --s3-prefix sam-app-prod
      - run: sam deploy --template-file .aws-sam/build/package.yaml --no-confirm-changeset --stack-name sam-app-prod --capabilities CAPABILITY_IAM --parameter-overrides Environment=prod

