name: Deploy to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Deploy to Dev
        # uses: aws-actions/aws-sam-cli-deploy@v1
        with:
          stack-name: sam-app-dev
          s3-bucket: aws-sam-cli-managed-default-samclisourcebucket-1rqnxsr0m1td6/sam-app-dev/
          region: us-west-1
          capabilities: CAPABILITY_IAM
