name: Deploy to Dev Environment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to Dev Environment
        uses: aws-actions/aws-sam-cli-deploy@v1
        with:
          stack-name: sam-app-dev
          region: us-west-1
          s3-bucket: sam-app-dev
          template-file: template.yaml
          capabilities: CAPABILITY_IAM
