name: SAM Deploy
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - run: sam build --use-container
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          #path: .aws-sam/build
          #name: Upload artifact to S3 bucket
      - run: aws s3 cp .aws-sam/build s3://github-artifact-test
  dev:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      #- run: sam build --use-container
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: .aws-sam/build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env dev
  test:
    runs-on: ubuntu-latest
    needs: [dev]
    #environment:
     # name: test
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      #- run: sam build --use-container
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: .aws-sam/build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env test
  prod:
    runs-on: ubuntu-latest
    needs: [test]
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      #- run: sam build --use-container
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          path: .aws-sam/build
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env prod

