name: Deploy SAM Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [ dev, test, prod ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      env:
        AWS_PROFILE: ${{ matrix.env }}
      run: aws configure set region us-west-1
    - name: Build and deploy SAM application
      run: |
        sam build
        sam deploy --no-confirm-changeset --config-env ${{ matrix.env }}
