name: SAM Deploy
on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install SAM CLI
      uses: aws-actions/setup-sam-cli@v1
    - name: Deploy Lambda Function
      run: sam build
      
  test:   
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Echo Hello, World!
      run: echo "Hello, World! Test"
  
  prod:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Echo Hello, World!
      run: echo "Hello, World!Production"
      

      uses: actions/checkout@v2
    - name: Install SAM CLI
      uses: aws-actions/setup-sam-cli@v1
    - name: Deploy Lambda Function
      run: sam deploy --template-file path/to/template.yml --stack-name lambda-stack --capabilities CAPABILITY_IAM --region us-east-1
